Repository zero-to-mastery/Animation-Nation, pull requests merged in 2020-10, with the labels that each got.

#891 added my work
  Art/adymoko/index.html
  Art/adymoko/style.css
  Art/adymoko/tired piggy.gif
Labels: Stale

#907 Update include.js
  include.js
Labels: Necessary Files Missing

#923 Made a simple meme animation lol
  Art/animation_gn/animation_gn.gif
  Art/animation_gn/index.html
  Art/animation_gn/style.css
  include.js
Labels: bug
