Repository zero-to-mastery/Animation-Nation, pull requests merged in 2023-10, with the labels that each got.

#1730 added my animation to the project
  Art/packman/giphy.gif
  Art/packman/packman.html
  Art/packman/style.css
  include.js
Labels: hacktoberfest-accepted

#1759 adding coffee cup
  Art/Alexandra2888/cup.css
  Art/Alexandra2888/cup.gif
  Art/Alexandra2888/cup.html
  include.js
Labels: invalid, Conflict Present

#1786 Richard's bouncing ball with shadow
  Art/Richard/animated.css
  Art/Richard/animated.html
  Art/Richard/bounce.gif.gif
  include.js
Labels: Changes Requested

#1785 SquBounce Animated Art
  Art/Sanusi/index.html
  Art/Sanusi/sanusi-animation-shot.jpg
  Art/Sanusi/sanusi-animation.gif
  Art/Sanusi/style.css
  include.js
Labels: Conflict Present, Changes Requested

#1849 Simple webanimation
  Art/MishC/circle.css
  Art/MishC/circle.html
  Art/MishC/magic_circle.gif
  include.js
Labels: Changes Requested

#1860 Added cube animation
  Art/Rishi/cube.gif
  Art/Rishi/cube.html
  Art/Rishi/style.css
  include.js
Labels: Changes Requested

#1866 Adding Pumpkin Ghost to Animation Nation.
  Art/Jason/pumpkin.css
  Art/Jason/pumpkin.gif
  Art/Jason/pumpkin.html
  include.js
Labels: Changes Requested

#1950 first open source contribution
  Art/mohdUsman-6508/wheel.css
  Art/mohdUsman-6508/wheel.html
  Art/mohdUsman-6508/wheel.png
  include.js
Labels: Changes Requested

#1966 add heart loading animation
  Art/maidxn/heart-loading-animate.gif
  Art/maidxn/index.html
  Art/maidxn/styles.css
  include.js
Labels: Changes Requested

#1965 Added gif
  Art/Luv/heart.png
  Art/Luv/index.html
  Art/Luv/style.css
  include.js
Labels: Changes Requested

#1980 Card animation
  Art/lucifer510/card.css
  Art/lucifer510/card.html
  Art/lucifer510/card.png
  include.js
Labels: invalid

#1975 First Simple loading animation
  include.js
Labels: Changes Requested

#1900 Added my file in Art folder which include my animation html,css,gif
  Art/BlueHeart0065/gun.css
  Art/BlueHeart0065/gun.gif
  Art/BlueHeart0065/gun.html
  include.js
Labels: Changes Requested

#1956 Include.js changes
  include.js
Labels: Changes Requested

#1961 Add Face animation
  Art/Pabitra/face animation gif.gif
  Art/Pabitra/index.html
  Art/Pabitra/style.css
  include.js
Labels: Changes Requested

#2009 ParzivalAFK Entry 1
  Art/ParzivalAFK/TwirlingSpheres.css
  Art/ParzivalAFK/TwirlingSpheres.gif
  Art/ParzivalAFK/TwirlingSpheres.html
  include.js
Labels: Changes Requested

#1892 Uploaded animatedfiles and modified include.js
  Art/AkashCss/AkashCssGif.gif
  Art/AkashCss/index.html
  Art/AkashCss/styles.css
  include.js
Labels: Conflict Present, Changes Requested

#1905 Added dynamic Letter Animation template
  Art/varshithab05/Letter_Animation.gif
  Art/varshithab05/indexp.html
  Art/varshithab05/stylep.css
  include.js
Labels: Changes Requested

#2005 Hacktoberfest Commit
  Art/Subramaniam-dot/animation.gif
  Art/Subramaniam-dot/snake.html
  Art/Subramaniam-dot/style.css
  include.js
Labels: Changes Requested

#2011 Parzival afk sun
  Art/ParzivalAFK/Animation1.gif
  Art/ParzivalAFK/HalfSpinPoints.css
  Art/ParzivalAFK/HalfSpinPoints.html
  Art/ParzivalAFK/ParzivalAFK_SUN.gif
  Art/ParzivalAFK/sun.css
  Art/ParzivalAFK/sun.html
  include.js
Labels: Changes Requested

#2098 Added Repo Status in the README.md
  README.md
Labels: enhancement

#2018 Added: spacecraft
  Art/manuelachamoso/index.html
  Art/manuelachamoso/space.gif
  Art/manuelachamoso/styles.css
  include.js
Labels: Changes Requested

#2084 Added Blooming flower animation
  Art/Asymtode712/blooming-flowers.gif
  Art/Asymtode712/gflower.css
  Art/Asymtode712/gflower.html
  Art/Asymtode712/growing-flower.gif
  Art/Asymtode712/index.html
  Art/Asymtode712/style.css
  include.js
Labels: Changes Requested

#2100 add profileImageAnimation
  Art/thiunuwan/index.html
  Art/thiunuwan/me3.jpeg
  Art/thiunuwan/profileAnimation.gif
  Art/thiunuwan/styles.css
  include.js
Labels: Changes Requested

#2104 Core/cleanup 231013
  Art/Arc/index.html
  Art/Lefie/index.html
  Art/Lefie/styles.css
  Art/Pabitra/face-animation.gif
  Art/ParzivalAFK/HalfSpinPoints.css
  Art/ParzivalAFK/HalfSpinPoints.html
  Art/ParzivalAFK/TargetLoadingBothColors.css
  Art/ParzivalAFK/TargetLoadingBothColors.html
  Art/RedHoodJT1988/index.html
  Art/RedHoodJT1988/styles.css
  Art/Sahil/animation.gif
  Art/SamrithaS/parrot.css
  Art/SamrithaS/parrot.html
  Art/Sayed-Husain/index.html
  Art/Sayed-Husain/style.css
  Art/TaniaZaitouny/index.html
  Art/TaniaZaitouny/style.css
  Art/Vivek-GuptaXCode/index.html
  Art/Vivek-GuptaXCode/styles.css
  Art/aaron-jacob/index.html
  Art/aaron-jacob/styles.css
  Art/ahmedalhamad7/index.html
  Art/ahmedalhamad7/static-picture.jpg
  Art/ahmedalhamad7/style.css
  Art/apu52/day-and-night-fox/index.html
  Art/apu52/day-and-night-fox/picture.jpeg
  Art/apu52/day-and-night-fox/style.css
  Art/brando161/index.html
  Art/brando161/style.css
  Art/lucifer510/text.css
  Art/lucifer510/text.html
  Art/manuelachamoso/index.html
  Art/manuelachamoso/styles.css
  Art/neha3423/index.html
  Art/neha3423/style.css
  Art/saikatsamanta/index.html
  Art/saikatsamanta/style.css
  Art/varian1/bouncing-ball.gif
  Art/varian1/index.html
  Art/varian1/styles.css
  README.md
  include.js
  index.html
  public/adjust.js
  public/images/ZTM.png
  public/images/colourpencils.png
  public/style.css
Labels: enhancement

#2110 Cassette animation
  Art/apu52/cassette animation.png
  Art/apu52/index.html
  Art/apu52/style.css
  include.js
Labels: Changes Requested

#2113 Gauravsaxena816 patch 1
  Art/gaurav816/index.html
  Art/gaurav816/loader.gif
  Art/gaurav816/style.css
  include.js
Labels: Changes Requested

#2120 Added Square Bouncing Animation
  Art/tvermaashutosh/animation.gif
  Art/tvermaashutosh/index.html
  Art/tvermaashutosh/style.css
  include.js
Labels: Changes Requested

#2021 Ball Hitting
  Art/Kamalesh-Seervi/balling-hitting.gif
  Art/Kamalesh-Seervi/index.css
  Art/Kamalesh-Seervi/index.html
  include.js
Labels: Changes Requested

#2102 Creating simple transition usin HTML and CSS
  Art/rajan4405/Animation.gif
  Art/rajan4405/app.css
  Art/rajan4405/index.html
  include.js
Labels: Changes Requested

#2119 Added rotating and scaling animation for a div
  Art/Abhishek1/Animation.png
  Art/Abhishek1/index.html
  Art/Abhishek1/styles.css
  include.js
Labels: Changes Requested

#2122 creating my own animation and updating the include.js file
  Art/philling1/animation.gif
  Art/philling1/index.html
  Art/philling1/style.css
  include.js
Labels: Changes Requested

#2131 GlowingStars
  Art/vivek/GlowingStars.css
  Art/vivek/GlowingStars.gif
  Art/vivek/GlowingStars.html
  include.js
Labels: Changes Requested

#2137 candle holder
  Art/czarjulius/candle.css
  Art/czarjulius/candle.gif
  Art/czarjulius/candle.html
Labels: Changes Requested

#2133 glowing flower animation
  Art/saurabhsingh720/GlowingFlower.gif
  Art/saurabhsingh720/GlowingFlower.html
  Art/saurabhsingh720/style.css
  include.js
Labels: Changes Requested

#2142 .
  Art/ahmedalhamad7/moon.css
  Art/ahmedalhamad7/moon.html
  Art/ahmedalhamad7/moon.png
  Art/ahmedalhamad7/static moon.png
  include.js
Labels: Changes Requested

#2176 Text Animation For Portfolio
  Art/Vinay_Adatiya/textanimation.css
  Art/Vinay_Adatiya/textanimation.gif
  Art/Vinay_Adatiya/textanimation.html
  include.js
Labels: Changes Requested

#2198 moving block
  Art/Soumyadeep_Garai/card.gif
  Art/Soumyadeep_Garai/index.html
  Art/Soumyadeep_Garai/style.css
  include.js
Labels: Changes Requested

#2250 Adding my animation project to the list
  Art/ruchircodes24/Score.gif
  Art/ruchircodes24/images/ball.png
  Art/ruchircodes24/images/football.png
  Art/ruchircodes24/images/goal-post.jpg
  Art/ruchircodes24/index.html
  Art/ruchircodes24/style.css
  include.js
Labels: hacktoberfest-accepted

#2242 Adding coffee machine animation
  Art/TejaJanakiRam/coffee_machine.gif
  Art/TejaJanakiRam/index.html
  Art/TejaJanakiRam/styles.css
  include.js
Labels: hacktoberfest-accepted

#2279 This is my first Art
  Art/samwillson2009/blueSquare.css
  Art/samwillson2009/blueSquare.gif
  Art/samwillson2009/blueSquare.html
  include.js
Labels: hacktoberfest-accepted

#2284 added my name in /include.js
  Art/Loading-Dot.gif
  Art/index.html
  Art/styles.css
Labels: Changes Requested

#2285 Update include.js
  include.js
Labels: question

#2288 added camera shutter animation and changed folder structure
  Art/manishjha-04/CameraShutter/camera-shutter.gif
  Art/manishjha-04/CameraShutter/index.html
  Art/manishjha-04/CameraShutter/style.css
  Art/manishjha-04/Cinematic/cinematic_animation.gif
  Art/manishjha-04/Cinematic/index.html
  Art/manishjha-04/Cinematic/style.css
  Art/manishjha-04/LoopLamina/Looplamina.gif
  Art/manishjha-04/LoopLamina/index.html
  Art/manishjha-04/LoopLamina/style.css
  include.js
Labels: hacktoberfest-accepted

#2289 Added a new square animation
  Art/romitp4l/css.css
  Art/romitp4l/gif.gif
  Art/romitp4l/html.html
  include.js
Labels: hacktoberfest-accepted

#2291 Added my art again
  Art/Moccasym/index.html
  Art/Moccasym/pacman.gif
  Art/Moccasym/style.css
  include.js
Labels: hacktoberfest-accepted

#2294 My first button animation
  Art/H-SM/button_animation_here.gif
  Art/H-SM/index.html
  Art/H-SM/style.css
  include.js
Labels: hacktoberfest-accepted

#2300 My 4th Animation
  Art/samwillson2009/circle2.css
  Art/samwillson2009/circle2.gif
  Art/samwillson2009/circle2.html
  include.js
Labels: hacktoberfest-accepted

#2304 removed incorrect file uploads
  Art/Devanshumasodke
  Art/index.html
  Art/styles.css
Labels: hacktoberfest-accepted

#2295 adding my new art
  Art/K-Wiczling/complex.css
  Art/K-Wiczling/complex.html
  Art/K-Wiczling/complex.png
  Art/K-Wiczling/square.css
  Art/K-Wiczling/square.html
  include.js
Labels: Changes Requested

#2287 Animation added to art directory
  Art/Aryan741x/animation-1.png
  Art/Aryan741x/index.html
  Art/Aryan741x/style.css
  include.js
Labels: Changes Requested

#2329 Update include.js
  Art/nharjes/ColorfulBackgroundDemo.gif
  Art/nharjes/index.html
  Art/nharjes/styles.css
  include.js
Labels: question

#2318 Added my animation
  Art/majidshakeelshawl/animate.gif
  Art/majidshakeelshawl/index.html
  Art/majidshakeelshawl/styles.css
  include.js
Labels: Changes Requested

#2345 Core/revamp proposition
  include.js
  index.html
  public/style.css
Labels: enhancement

#2151 Add Fayezkhan1
  Art/Fayezkhan1/art.gif
  Art/Fayezkhan1/index.html
  Art/Fayezkhan1/style.css
  include.js
Labels: Changes Requested

#1881 Added Favicon #1869
  index.html
Labels: Changes Requested

#2276 ball_animation
  Art/daemonvk18/animation.gif
  Art/daemonvk18/animation.html
  Art/daemonvk18/styles.css
  include.js
Labels: Changes Requested

#2228 Added button hover animation
  Art/shag1802/hover_ani.gif
  Art/shag1802/index.html
  Art/shag1802/style.css
  include.js
Labels: Changes Requested

#2370 Animation added
  Art/rudrakushwaha/Arrows.gif
  Art/rudrakushwaha/index.html
  Art/rudrakushwaha/style.css
  include.js
Labels: hacktoberfest-accepted

#2187 Added a new animation : "Bouncing Ball with colour change"
  Art/Vivek-GuptaXCode/bouncing-ball.css
  Art/Vivek-GuptaXCode/bouncing-ball.gif
  Art/Vivek-GuptaXCode/bouncing-ball.html
  include.js
Labels: Changes Requested

#2189 amandeepsinghparihar
  Art/amandeep-singh-parihar/Screenshot_2023-10-18_141651.png
  Art/amandeep-singh-parihar/loader/index.html
  Art/amandeep-singh-parihar/loader/style.css
  include.js
Labels: Changes Requested

#2211 Adding the first project: Animation
  Art/norib016/art.css
  Art/norib016/art.gif
  Art/norib016/art.html
  include.js
Labels: Changes Requested

#2381 Added Slide-In Animation
  Art/kalkeshwar/index.html
  Art/kalkeshwar/sliderightanimation.gif
  Art/kalkeshwar/style.css
  include.js
Labels: hacktoberfest-accepted

#2310 Loader Animation
  Art/rishika-on-git/index.html
  Art/rishika-on-git/result.gif
  Art/rishika-on-git/styles.css
  include.js
Labels: hacktoberfest-accepted

#2286 Add a tiled loader
  Art/tmsagarofficial/anim2.css
  Art/tmsagarofficial/anim2.gif
  Art/tmsagarofficial/anim2.html
  include.js
Labels: Changes Requested

#2330 3D Rotating Cube Animation
  Art/MananSharma2710/Cube.gif
  Art/MananSharma2710/index.html
  Art/MananSharma2710/style.css
  include.js
Labels: Changes Requested

#2331 colorful rotating 3d cube (horizontal rotating)
  Art/Abhika3021/Cube.gif
  Art/Abhika3021/index.html
  Art/Abhika3021/style.css
  include.js
Labels: Changes Requested

#2348 Women in STEM addition
  Art/Lucile-Tech/cardproject.png
  Art/Lucile-Tech/index.html
  Art/Lucile-Tech/style.css
  include.js
Labels: hacktoberfest-accepted

#2350 added my animation
  Art/supriya/galaxy.css
  Art/supriya/galaxy.gif
  Art/supriya/galaxy.html
  include.js
Labels: Changes Requested

#2372 added art
  Art/hassan02/ezgif.com-video-to-gif.gif
  Art/hassan02/index.html
  Art/hassan02/style.css
  include.js
Labels: hacktoberfest-accepted

#2373 add my first animation work
  Art/marjsky/awesome-2.gif
  Art/marjsky/index.html
  Art/marjsky/style.css
  include.js
Labels: hacktoberfest-accepted

#2385 Gradient loading-spinner
  Art/fi1na/Loading-spinner.gif
  Art/fi1na/index.html
  Art/fi1na/style.css
  include.js
Labels: hacktoberfest-accepted

#2384 Added Ping Pong Animation
  Art/JeevaRamanathan/index.html
  Art/JeevaRamanathan/ping-pong.gif
  Art/JeevaRamanathan/style.css
  include.js
Labels: hacktoberfest-accepted

#2391 adding my art to the project
  Art/cpasigna90/AnimationColorBox.gif
  Art/cpasigna90/boxcolorchange.html
  Art/cpasigna90/style.css
  include.js
Labels: hacktoberfest-accepted

#2277 Added Square shape color changing animation
  Art/divyansharya8826/index.css
  Art/divyansharya8826/index.html
  Art/divyansharya8826/square.gif
  include.js
Labels: Necessary Files Missing, Changes Requested

#2394 Added kinetic_loading art for graphics
  Art/urjabahad/kinetic_loading.gif
  Art/urjabahad/kinetic_loading.html
  include.js
Labels: Changes Requested

#2416 Added earth animation
  Art/stormworm9/EarthAnimation/Earth.html
  Art/stormworm9/EarthAnimation/earth.gif
  Art/stormworm9/EarthAnimation/style.css
  include.js
Labels: Conflict Present
