Repository zero-to-mastery/Animation-Nation, pull requests merged in 2024-10, with the labels that each got.

#2618 Adding Bouncing ball
  Art/jeevaramanathan-bouncingball/index.html
  Art/jeevaramanathan-bouncingball/styles.css
Labels: Changes Requested

#2619 Add a pull request template
  .github/pull_request_template.md
Labels: documentation

#2625 animated artwork by Pauljd1
  Art/Pauljd1-Pumpkin/index.html
  Art/Pauljd1-Pumpkin/styles.css
  README.md
Labels: Changes Requested

#2626 Added loading dino animation
  Art/bandhan-majumder-loadingDino/index.html
  Art/bandhan-majumder-loadingDino/style.css
Labels: Changes Requested

#2631 smitthakore-Art
  Art/smitthakore-oreo/index.html
  Art/smitthakore-oreo/styles.css
Labels: hacktoberfest-accepted

#2632 Request to Merge Typewriter Animation Feature
  Art/BaraniVA-Typewriter/index.html
  Art/BaraniVA-Typewriter/styles.css
Labels: Changes Requested

#2641 Orbital Motion Animation
  Art/SagarVerma893-orbitalMotion/index.html
  Art/SagarVerma893-orbitalMotion/styles.css
Labels: Changes Requested

#2645 Animated SignUp Form
  Art/Yadnyesh-Dashpute-AnimatedForm/index.html
  Art/Yadnyesh-Dashpute-AnimatedForm/styles.css
Labels: hacktoberfest-accepted

#2652 Added Hand Animation Effect
  Art/somnath0904-HandAnimation/index.html
  Art/somnath0904-HandAnimation/styles.css
Labels: Changes Requested

#2656 Animation effects on a picture .it includes Bounce,Rotate,Colour Change,Scale on hovering
  Art/nabinkumarshaw-Animation/index.html
  Art/nabinkumarshaw-Animation/styles.css
Labels: hacktoberfest-accepted

#2657 Briancheung1 branch
  Art/BrianCheung1-Balloons/index.html
  Art/BrianCheung1-Balloons/styles.css
Labels: Changes Requested

#2660 Added animation Twilight Voyage
  Art/shuaixr-twilight_voyage/index.html
  Art/shuaixr-twilight_voyage/styles.css
Labels: Changes Requested

#2671 Added Scroll Animation
  Art/SumitDutta007-scroll/index.html
  Art/SumitDutta007-scroll/styles.css
Labels: hacktoberfest-accepted

#2688 aayu5hgit-LoaderAnimation PR
  Art/aayu5hgit-LoaderAnimation/index.html
  Art/aayu5hgit-LoaderAnimation/styles.css
Labels: Changes Requested

#2690 added new animation - spinning loader with a pulsating effect
  Art/AlexanderSanin-spinning-loader/index.html
  Art/AlexanderSanin-spinning-loader/styles.css
Labels: hacktoberfest-accepted

#2670 Added a scary face to collection of the art nation | fullspeccoder
  Art/fullspeccoder-scaryface/index.html
  Art/fullspeccoder-scaryface/styles.css
Labels: Changes Requested

#2692 Loader_Animation
  Art/Nishankulal03-loader/index.css
  Art/Nishankulal03-loader/index.css.map
  Art/Nishankulal03-loader/index.html
  Art/Nishankulal03-loader/index.scss
Labels: hacktoberfest-accepted

#2693 added Hindu-swastika animation
  Art/dev1abhi-Hindu-Swastika/index.html
  Art/dev1abhi-Hindu-Swastika/styles.css
Labels: hacktoberfest-accepted

#2695 Flickering Neon Sign
  Art/SagarVerma893-Flickering Neon Sign/index.html
  Art/SagarVerma893-Flickering Neon Sign/styles.css
Labels: hacktoberfest-accepted

#2696 3D flip Animation
  Art/kishan-25-3D/index.html
  Art/kishan-25-3D/styles.css
Labels: hacktoberfest-accepted

#2694 added animation
  Art/THE-ASHUTOSH-button-animation/index.html
  Art/THE-ASHUTOSH-button-animation/style.css
Labels: hacktoberfest-accepted

#2701 animation-done
  Art/hanisntsolo-verticalballsbounce/index.html
  Art/hanisntsolo-verticalballsbounce/styles.css
Labels: Changes Requested

#2704 SammyUrfen - A pendulum on Click
  Art/SammyUrfen-pendulum/index.html
  Art/SammyUrfen-pendulum/styles.css
Labels: hacktoberfest-accepted

#2703 Add Celestial Dance animation
  Art/Kaif-Azmi-Celestial-Dance/index.html
  Art/Kaif-Azmi-Celestial-Dance/styles.css
Labels: hacktoberfest-accepted

#2705 Alienx5499 my art
  Art/alienx5499-profilecard/index.html
  Art/alienx5499-profilecard/styles.css
Labels: Changes Requested

#2706 Added Hacktoberfest animation files
  Art/Kaif-Azmi-Hacktoberfest-Animation/index.html
  Art/Kaif-Azmi-Hacktoberfest-Animation/styles.css
Labels: hacktoberfest-accepted

#2707 Added index.html and style.css
  Art/Dhairya-A-Mehra-spininng_cube/index.html
  Art/Dhairya-A-Mehra-spininng_cube/styles.css
Labels: Changes Requested

#2718 Animated Button with Hover Effects
  Art/Dhruv-Davda-AnimatedButton/index.html
  Art/Dhruv-Davda-AnimatedButton/meta.json
  Art/Dhruv-Davda-AnimatedButton/styles.css
Labels: hacktoberfest-accepted

#2722 Add animation of the earth/moon/sun
  Art/maidxn-solarsystem/index.html
  Art/maidxn-solarsystem/meta.json
  Art/maidxn-solarsystem/styles.css
Labels: hacktoberfest-accepted

#2712 3D Flip Card Animation
  Art/SagarVerma893-3D Flip Card Animation/index.html
  Art/SagarVerma893-3D Flip Card Animation/meta.json
  Art/SagarVerma893-3D Flip Card Animation/styles.css
Labels: hacktoberfest-accepted

#2699 Added my Animations- A rotating 3-D Cube Animation
  Art/Anurag-singh-thakur-Rotating Sqaure/index.html
  Art/Anurag-singh-thakur-Rotating Sqaure/styles.css
Labels: Changes Requested

#2717 Haloween branch
  Art/Isabelle36-Halloween/index.html
  Art/Isabelle36-Halloween/meta.json
  Art/Isabelle36-Halloween/styles.css
Labels: Changes Requested

#2726 Added Animation
  Art/guranshdeol-CardFlip/index.html
  Art/guranshdeol-CardFlip/meta.json
  Art/guranshdeol-CardFlip/styles.css
Labels: Changes Requested

#2727 Typing Animation
  Art/SagarVerma893-Typing Animation/index.html
  Art/SagarVerma893-Typing Animation/meta.json
  Art/SagarVerma893-Typing Animation/styles.css
Labels: hacktoberfest-accepted

#2725 Gauravbalade myartwork
  Art/gauravbalade-myartwork/index.html
  Art/gauravbalade-myartwork/meta.json
  Art/gauravbalade-myartwork/styles.css
Labels: Changes Requested

#2723 Added the Welcome animation
  Art/KC1064-Welcome/index.html
  Art/KC1064-Welcome/meta.json
  Art/KC1064-Welcome/styles.css
Labels: hacktoberfest-accepted

#2730 added my cool animation
  Art/HossamGouda-CirclePulse/index.html
  Art/HossamGouda-CirclePulse/meta.json
  Art/HossamGouda-CirclePulse/styles.css
Labels: hacktoberfest-accepted

#2731 Hacktoberfest 2024 pr
  Art/ornitcg-coloredsquares/index.html
  Art/ornitcg-coloredsquares/meta.json
  Art/ornitcg-coloredsquares/styles.css
Labels: hacktoberfest-accepted

#2734 Hactoberfest2024 - my eclipse animation
  Art/ornitcg-eclipse/index.html
  Art/ornitcg-eclipse/meta.json
  Art/ornitcg-eclipse/styles.css
Labels: hacktoberfest-accepted

#2735 Hacktoberfest2024 my thirs Animation-Nation
  Art/ornitcg-rotation/index.html
  Art/ornitcg-rotation/meta.json
  Art/ornitcg-rotation/styles.css
Labels: hacktoberfest-accepted

#2732 Added a lotus that pulsates and changes colors
  Art/aarushsaboo-neonsign/index.html
  Art/aarushsaboo-neonsign/meta.json
  Art/aarushsaboo-neonsign/styles.css
Labels: Changes Requested

#2738 Profoundlyparker Shop Like You Give a Damn Animation
  Art/ProfoundlyParker-Shop-Like-You-Give-a-Damn/index.html
  Art/ProfoundlyParker-Shop-Like-You-Give-a-Damn/meta.json
  Art/ProfoundlyParker-Shop-Like-You-Give-a-Damn/styles.css
Labels: hacktoberfest-accepted

#2740 Add rotating square animation
  Art/terrifricker-rotatingSquare/index.html
  Art/terrifricker-rotatingSquare/meta.json
  Art/terrifricker-rotatingSquare/styles.css
Labels: hacktoberfest-accepted

#2715 Animated cards
  Art/PragyaTripathi990-cardsAnimation/index.html
  Art/PragyaTripathi990-cardsAnimation/meta.json
  Art/PragyaTripathi990-cardsAnimation/styles.css
Labels: Changes Requested

#2739 Hacktoberfest2024 - eyes animation
  Art/ornitcg-blink/index.html
  Art/ornitcg-blink/meta.json
  Art/ornitcg-blink/styles.css
Labels: Changes Requested

#2737 add simple linear colorful loader
  Art/Navdeepsingh4298-linearColorfulLoader/index.html
  Art/Navdeepsingh4298-linearColorfulLoader/meta.json
  Art/Navdeepsingh4298-linearColorfulLoader/styles.css
Labels: Changes Requested

#2741 2 animations by chaitraDev
  Art/chaitraDev_pulsating_circles/index.html
  Art/chaitraDev_pulsating_circles/meta.json
  Art/chaitraDev_pulsating_circles/styles.css
  Art/chaitraDev_spiralMove/index.html
  Art/chaitraDev_spiralMove/meta.json
  Art/chaitraDev_spiralMove/styles.css
Labels: Changes Requested

#2742 AtomAnimation
  Art/AvinashKumar0923-atomAnimation/index.html
  Art/AvinashKumar0923-atomAnimation/meta.json
  Art/AvinashKumar0923-atomAnimation/styles.css
Labels: Changes Requested

#2747 Added Bouncing Effects
  Art/DEBASISH077-BouncingEffect/index.html
  Art/DEBASISH077-BouncingEffect/meta.json
  Art/DEBASISH077-BouncingEffect/styles.css
Labels: hacktoberfest-accepted

#2749 Hacktoberfest 2024 PR
  Art/surjayankar-InfiniteGridBackground/index.html
  Art/surjayankar-InfiniteGridBackground/meta.json
  Art/surjayankar-InfiniteGridBackground/styles.css
Labels: hacktoberfest-accepted

#2750 Added a image grid animation
  Art/KC1064-Grid-Animation/index.html
  Art/KC1064-Grid-Animation/meta.json
  Art/KC1064-Grid-Animation/styles.css
Labels: Changes Requested

#2757 Spaceship
  Art/Debajyati-SPACESHIP/index.html
  Art/Debajyati-SPACESHIP/meta.json
  Art/Debajyati-SPACESHIP/styles.css
Labels: Changes Requested

#2766 dog animation
  Art/shanolhere-dogAnimation/index.html
  Art/shanolhere-dogAnimation/meta.json
  Art/shanolhere-dogAnimation/styles.css
Labels: hacktoberfest-accepted

#2770 adding my art
  Art/cljarvis-octArt/index.html
  Art/cljarvis-octArt/meta.json
  Art/cljarvis-octArt/styles.css
Labels: hacktoberfest-accepted

#2767 Refactor profile card design for enhanced visual appeal and interactivity
  Art/RAj5517-animated_profilecard/index.html
  Art/RAj5517-animated_profilecard/meta.json
  Art/RAj5517-animated_profilecard/styles.css
Labels: Changes Requested

#2772 Awesome Bubble Animations
  Art/AbdulRehmanGHub-NeonBorderAnimations/index.html
  Art/AbdulRehmanGHub-NeonBorderAnimations/meta.json
  Art/AbdulRehmanGHub-NeonBorderAnimations/styles.css
Labels: hacktoberfest-accepted

#2778 buttons wiggling animation
  Art/AfreenInnovates-buttonswiggle/index.html
  Art/AfreenInnovates-buttonswiggle/meta.json
  Art/AfreenInnovates-buttonswiggle/styles.css
Labels: hacktoberfest-accepted

#2779 Add flower animation
  Art/maidxn-flower/index.html
  Art/maidxn-flower/meta.json
  Art/maidxn-flower/styles.css
Labels: hacktoberfest-accepted

#2771 "Flickering Stars" animation by RaHasib
  Art/RaHasib-flickeringStars/index.html
  Art/RaHasib-flickeringStars/meta.json
  Art/RaHasib-flickeringStars/styles.css
Labels: hacktoberfest-accepted

#2769 I added my files to join in the opensource contribution Anime's Art
  Art/Emmykeys101-animeArt/index.html
  Art/Emmykeys101-animeArt/meta.json
  Art/Emmykeys101-animeArt/styles.css
Labels: Changes Requested

#2782 Wave animation
  Art/maidx-waveText/index.html
  Art/maidx-waveText/meta.json
  Art/maidx-waveText/styles.css
Labels: hacktoberfest-accepted

#2784 cube rotation
  Art/AfreenInnovates-cube/index.html
  Art/AfreenInnovates-cube/meta.json
  Art/AfreenInnovates-cube/styles.css
Labels: hacktoberfest-accepted

#2777 Rocket
  Art/HossamGouda-Rocket-Launch/index.html
  Art/HossamGouda-Rocket-Launch/meta.json
  Art/HossamGouda-Rocket-Launch/styles.css
Labels: Changes Requested

#2787 Indian flag animation
  Art/AfreenInnovates-Indianflag/index.html
  Art/AfreenInnovates-Indianflag/meta.json
  Art/AfreenInnovates-Indianflag/styles.css
Labels: hacktoberfest-accepted

#2775 Solar system animation
  Art/HossamGouda-Solar-System/index.html
  Art/HossamGouda-Solar-System/meta.json
  Art/HossamGouda-Solar-System/styles.css
Labels: Changes Requested

#2793 Adding Loading status animation
  Art/Codeioholic-LoadingScreen/index.html
  Art/Codeioholic-LoadingScreen/meta.json
  Art/Codeioholic-LoadingScreen/styles.css
Labels: hacktoberfest-accepted

#2789 A beautiful animation added
  Art/Kaif-Azmi-Colour-Fill/index.html
  Art/Kaif-Azmi-Colour-Fill/meta.json
  Art/Kaif-Azmi-Colour-Fill/styles.css
  Art/Kaif-Azmi-SubmitBtn-Animation/index.html
  Art/Kaif-Azmi-SubmitBtn-Animation/meta.json
  Art/Kaif-Azmi-SubmitBtn-Animation/styles.css
Labels: duplicate, Changes Requested

#2785 Horizontal Car Animation Effect
  Art/DEBASISH077-BouncingEffect/meta.json
  Art/DEBASISH077-Horizontal_Car_Animation/Index.html
  Art/DEBASISH077-Horizontal_Car_Animation/Style.css
  Art/DEBASISH077-Horizontal_Car_Animation/meta.json
Labels: question

#2803 cube_grow_rotate
  Art/AfreenInnovates-cube_grow_rotate/index.html
  Art/AfreenInnovates-cube_grow_rotate/meta.json
  Art/AfreenInnovates-cube_grow_rotate/styles.css
Labels: hacktoberfest-accepted

#2792 add bouncing ball to the project
  Art/shrlaw-bouncing/index.html
  Art/shrlaw-bouncing/meta.json
  Art/shrlaw-bouncing/styles.css
Labels: Changes Requested

#2806 animated_curtain
  Art/AfreenInnovates-animated_curtain/index.html
  Art/AfreenInnovates-animated_curtain/meta.json
  Art/AfreenInnovates-animated_curtain/styles.css
Labels: hacktoberfest-accepted

#2810 Animated ZTM letters
  Art/kasunjayasanka-ZTM-letters-animation/index.html
  Art/kasunjayasanka-ZTM-letters-animation/meta.json
  Art/kasunjayasanka-ZTM-letters-animation/styles.css
  Art/kasunjayasanka-fetching-animation/index.html
  Art/kasunjayasanka-fetching-animation/meta.json
  Art/kasunjayasanka-fetching-animation/styles.css
Labels: hacktoberfest-accepted

#2820 Added a BouncingBall animation
  Art/venkateeshh-bouncingball/index.html
  Art/venkateeshh-bouncingball/meta.json
  Art/venkateeshh-bouncingball/styles.css
Labels: hacktoberfest-accepted

#2827 sadhika tadinada pr 4
  Art/sadhikatadinada-nebula-animation/index.html
  Art/sadhikatadinada-nebula-animation/meta.json
  Art/sadhikatadinada-nebula-animation/styles.css
Labels: hacktoberfest-accepted

#2830 feature: added animation
  Art/Tanisha800-bounceBall/index.html
  Art/Tanisha800-bounceBall/meta.json
  Art/Tanisha800-bounceBall/styles.css
Labels: hacktoberfest-accepted

#2828 Spiderman Animation
  Art/Avneets0419-spidermananimation/index.html
  Art/Avneets0419-spidermananimation/meta.json
  Art/Avneets0419-spidermananimation/styles.css
Labels: hacktoberfest-accepted

#2841 feature: added a wave loading animation
  Art/vridhichaudhary-waveAnimation/index.html
  Art/vridhichaudhary-waveAnimation/meta.json
  Art/vridhichaudhary-waveAnimation/styles.css
Labels: hacktoberfest-accepted

#2842 deleted the image and renamed my folder and addd animation
  Art/parthrajsinghbhati-pulsatingcircle/index.html
  Art/parthrajsinghbhati-pulsatingcircle/meta.json
  Art/parthrajsinghbhati-pulsatingcircle/styles.css
Labels: hacktoberfest-accepted

#2838 Adding Quantum Portal Animation to Animation Nation
  Art/ARYPROGRAMMER-Quantum_Portal_Animation/index.html
  Art/ARYPROGRAMMER-Quantum_Portal_Animation/meta.json
  Art/ARYPROGRAMMER-Quantum_Portal_Animation/styles.css
Labels: Changes Requested

#2848 Added a card flipping interactive animation
  Art/Kaif-Azmi-Animation-Done/index.html
  Art/Kaif-Azmi-Animation-Done/meta.json
  Art/Kaif-Azmi-Animation-Done/styles.css
Labels: hacktoberfest-accepted

#2849 katkatniss-add an art
  Art/katkatniss-makeAHalloweenPumpkin/index.html
  Art/katkatniss-makeAHalloweenPumpkin/meta.json
  Art/katkatniss-makeAHalloweenPumpkin/styles.css
Labels: hacktoberfest-accepted

#2791 violin87-activeSquares
  Art/SumitDutta007-bubbles/styles.css
  Art/violin87-activeSquares/index.html
  Art/violin87-activeSquares/meta.json
  Art/violin87-activeSquares/styles.css
Labels: Necessary Files Missing, Changes Requested

#2728 chore: add prettier workflow
  .github/workflows/post-merge.yml
  .prettierignore
  README.md
  package-lock.json
  package.json
Labels: enhancement, Changes Requested

#2818 maintainance_remove-automate-meta-and-fix-contributions
  Art/DEBASISH077-CoffeeMachine/icon.png
  Art/DEBASISH077-CoffeeMachine/index.html
  Art/DEBASISH077-CoffeeMachine/meta.json
  Art/DEBASISH077-CoffeeMachine/styles.css
  Art/kasunjayasanka-fetching-animation/index.html
  Art/kasunjayasanka-fetching-animation/meta.json
  Art/kasunjayasanka-fetching-animation/styles.css
  generators/__fixWithMetaData.js
  generators/generateCards.js
  public/cards.json
Labels: enhancement

#2862 Created JackOlantern animation
  Art/Catrina-W-JackOLantern/index.html
  Art/Catrina-W-JackOLantern/meta.json
  Art/Catrina-W-JackOLantern/styles.css
Labels: hacktoberfest-accepted

#2819 Feature1
  Art/AMRUTHA-BYSANI-LoadingColoursAnimation/index.html
  Art/AMRUTHA-BYSANI-LoadingColoursAnimation/meta.json
  Art/AMRUTHA-BYSANI-LoadingColoursAnimation/styles.css
Labels: Changes Requested

#2846 made a rolling box on a hill animation
  Art/Tenatic-X-RotatingBox/index.html
  Art/Tenatic-X-RotatingBox/meta.json
  Art/Tenatic-X-RotatingBox/styles.css
Labels: Changes Requested

#2861 Added cool gradient animation to text
  Art/NotIncorecc-coolGradientText/index.html
  Art/NotIncorecc-coolGradientText/meta.json
  Art/NotIncorecc-coolGradientText/styles.css
Labels: Changes Requested

#2870 add: waving flag animation
  Art/hoangnv170752-wavingflag/index.html
  Art/hoangnv170752-wavingflag/meta.json
  Art/hoangnv170752-wavingflag/styles.css
Labels: hacktoberfest-accepted

#2872 Added Morphing Blob Animation under Hacktoberfest
  Art/guranshdeol-morphingblob/index.html
  Art/guranshdeol-morphingblob/meta.json
  Art/guranshdeol-morphingblob/styles.css
Labels: hacktoberfest-accepted

#2873 Immersive 3 d billboard
  Art/mitul-bhatia-keyboardanimation/index.html
  Art/mitul-bhatia-keyboardanimation/meta.json
  Art/mitul-bhatia-keyboardanimation/styles.css
Labels: hacktoberfest-accepted

#2853 Added Animations
  Art/mitulBhatia-abs/icon.png
  Art/mitulBhatia-abs/index.html
  Art/mitulBhatia-abs/meta.json
  Art/mitulBhatia-abs/styles.css
Labels: Stale, Changes Requested

#2874 BouncingBall
  Art/vedpawar2254-bouncingball/index.html
  Art/vedpawar2254-bouncingball/meta.json
  Art/vedpawar2254-bouncingball/styles.css
Labels: hacktoberfest-accepted

#2875 Radar Scanner Animation added under HacktoberFest
  Art/guranshdeol-RadarScannarAnimation/index.html
  Art/guranshdeol-RadarScannarAnimation/meta.json
  Art/guranshdeol-RadarScannarAnimation/styles.css
Labels: hacktoberfest-accepted

#2876 Loader animation
  Art/shanolhere-dogAnimation/styles.css
  Art/shanolhere-loaderAnimation/index.html
  Art/shanolhere-loaderAnimation/meta.json
  Art/shanolhere-loaderAnimation/styles.css
Labels: hacktoberfest-accepted

#2878 Added A Disco ball animation
  Art/Voidedcrystal-disco/index.html
  Art/Voidedcrystal-disco/meta.json
  Art/Voidedcrystal-disco/styles.css
Labels: hacktoberfest-accepted
