Repository zero-to-mastery/Animation-Nation, pull requests merged in 2025-10, with the labels that each got.

#3001 feat: add digital-rain animation by bhupeshk3014
  Art/bhupeshk3014-digital-rain/index.html
  Art/bhupeshk3014-digital-rain/meta.json
  Art/bhupeshk3014-digital-rain/styles.css
Labels: hacktoberfest-accepted

#3002 feat: add pendulum animation by liketiger
  Art/liketiger-pendulum/index.html
  Art/liketiger-pendulum/meta.json
  Art/liketiger-pendulum/styles.css
  package-lock.json
Labels: hacktoberfest-accepted

#3003 To add cyber rader animation art
  Art/nithinu2802-cyber-radar/index.html
  Art/nithinu2802-cyber-radar/meta.json
  Art/nithinu2802-cyber-radar/styles.css
Labels: hacktoberfest-accepted, Changes Requested

#3006 Added a new animation of wave grid
  Art/mrkc2303-wave-grid/index.html
  Art/mrkc2303-wave-grid/meta.json
  Art/mrkc2303-wave-grid/styles.css
Labels: hacktoberfest-accepted

#3007 Added a new animation on neon radar
  Art/mrkc2303-neon-radar/index.html
  Art/mrkc2303-neon-radar/meta.json
  Art/mrkc2303-neon-radar/styles.css
Labels: hacktoberfest-accepted

#3009 Added a new animation of eclipse
  Art/mrkc2303-eclipse/index.html
  Art/mrkc2303-eclipse/meta.json
  Art/mrkc2303-eclipse/styles.css
Labels: hacktoberfest-accepted

#3012 feat : add fab-c14 3d dna Animation
  Art/fab-c14-3D-Dna/index.html
  Art/fab-c14-3D-Dna/meta.json
  Art/fab-c14-3D-Dna/styles.css
Labels: hacktoberfest-accepted

#3015 candle animation added
  Art/Annamalai24500-candle/index.html
  Art/Annamalai24500-candle/meta.json
  Art/Annamalai24500-candle/styles.css
Labels: hacktoberfest-accepted

#3016 Added a new animation pixel spiral
  Art/mrkc2303-pixel-spiral/index.html
  Art/mrkc2303-pixel-spiral/meta.json
  Art/mrkc2303-pixel-spiral/styles.css
Labels: hacktoberfest-accepted

#3031 feat: add reflecting star animation by liketiger
  Art/liketiger-reflecting-star/index.html
  Art/liketiger-reflecting-star/meta.json
  Art/liketiger-reflecting-star/styles.css
Labels: hacktoberfest-accepted

#3033 feat: add spinning top animation by liketiger
  Art/liketiger-spinning-top/index.html
  Art/liketiger-spinning-top/meta.json
  Art/liketiger-spinning-top/styles.css
Labels: hacktoberfest-accepted

#3028 Add solar system animation
  Art/Bharath-dev05-solar-system/index.html
  Art/Bharath-dev05-solar-system/meta.json
  Art/Bharath-dev05-solar-system/styles.css
Labels: Changes Requested

#3035 Add waterfall animation.
  Art/Bharath-dev05-water-fall/index.html
  Art/Bharath-dev05-water-fall/meta.json
  Art/Bharath-dev05-water-fall/styles.css
Labels: Changes Requested

#3027 Adding cloud animation
  Art/Bharath-dev05-clouds/index.html
  Art/Bharath-dev05-clouds/meta.json
  Art/Bharath-dev05-clouds/styles.css
Labels: Changes Requested

#3037 Added searching Animation
  Art/Saptarshi1984-searching/index.html
  Art/Saptarshi1984-searching/meta.json
  Art/Saptarshi1984-searching/styles.css
Labels: hacktoberfest-accepted

#3038 Add falling leaves animation.
  Art/Bharath-dev05-falling-leaves/index.html
  Art/Bharath-dev05-falling-leaves/meta.json
  Art/Bharath-dev05-falling-leaves/styles.css
Labels: hacktoberfest-accepted

#3040 feat: add missile hitting target infinite CSS animation
  Art/huzfm-missile/index.html
  Art/huzfm-missile/meta.json
  Art/huzfm-missile/styles.css
Labels: hacktoberfest-accepted

#3044 Vatsakala neon morph grid
  Art/Vatsakala-neon-morph-grid/index.html
  Art/Vatsakala-neon-morph-grid/meta.json
  Art/Vatsakala-neon-morph-grid/styles.css
Labels: hacktoberfest-accepted

#3049 Loading animation using CSS and HTML - stick man
  Art/chandra-durgampudi-loading-stick-man/index.html
  Art/chandra-durgampudi-loading-stick-man/meta.json
  Art/chandra-durgampudi-loading-stick-man/styles.css
Labels: hacktoberfest-accepted

#3050 Cljarvis goal
  Art/cljarvis-goal/index.html
  Art/cljarvis-goal/meta.json
  Art/cljarvis-goal/styles.css
Labels: hacktoberfest-accepted

#3055 add cube loader with glowing, rotating animation
  Art/jayantghadge-cube-loader/index.html
  Art/jayantghadge-cube-loader/meta.json
  Art/jayantghadge-cube-loader/styles.css
Labels: hacktoberfest-accepted

#3061 Added my CSS animation “UFO in sky” for Hacktoberfest
  Art/ravikantchauhan246-ufo-in-sky/index.html
  Art/ravikantchauhan246-ufo-in-sky/meta.json
  Art/ravikantchauhan246-ufo-in-sky/styles.css
Labels: hacktoberfest-accepted

#3062 Added in Moonlit Sky in Art Folder
  Art/Ujjansh05-Night-Sky/index.html
  Art/Ujjansh05-Night-Sky/meta.json
  Art/Ujjansh05-Night-Sky/styles.css
Labels: hacktoberfest-accepted

#3068 first commit
  Art/IshaaqDaahir-northern-aurora/index.html
  Art/IshaaqDaahir-northern-aurora/meta.json
  Art/IshaaqDaahir-northern-aurora/styles.css
Labels: hacktoberfest-accepted
